### ISSUE TITLE
As a content creator, I would like to gather data from around the user to determine hiking trails in the areas

### ISSUE THREAD

**Issue by mmichelon** [ChicoState/HikeLocator#12]
Is this too similar to "finding a hike nearby"?

**Comment by lwommack** [comment]
I agree that this might be similar to issue #5. It would be different if we are hoping to populate our database with an automatic scan of the app user's immediate area to find hikes we don't have near them and add them to our database? Like will we have a subroutine that looks up surrounding areas of users and automatically scrapes hike information? If we are that will be very difficult.
